In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
# Dot product
u * v

array([ 2,  0,  0, 12])

In [7]:
np.dot(u, v)

np.int64(14)

In [8]:
u.dot(v)

np.int64(14)

In [10]:
u = np.array(
    [[3, 1, 2],
     [4, 5, 7],
     [9, 6, 8]]
)
v = np.array(
    [[9, 1, 3],
     [2, 6, 7],
     [8, 4, 5]]
)

In [13]:
u.dot(v)

array([[ 45,  17,  26],
       [102,  62,  82],
       [157,  77, 109]])

In [14]:
np.matmul(u,v)

array([[ 45,  17,  26],
       [102,  62,  82],
       [157,  77, 109]])

In [15]:
u @ v

array([[ 45,  17,  26],
       [102,  62,  82],
       [157,  77, 109]])

In [17]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
w = np.matmul(u,v)
w

array([[ 45,  17,  26],
       [102,  62,  82],
       [157,  77, 109]])

In [19]:
np.matmul(w,I)

array([[ 45.,  17.,  26.],
       [102.,  62.,  82.],
       [157.,  77., 109.]])

Let's demonstrate the following

$$
X X^{-1} = X^{-1} X = I
$$

In [28]:
np.matmul(w, np.linalg.inv(w)).round()

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [29]:
np.matmul(np.linalg.inv(w), w).round()

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [ 0.,  0.,  1.]])

$$
(AB)(B^{-1} A^{-1}) = (B^{-1} A^{-1})(AB) = I
$$

In [24]:
w = np.matmul(u, v)
w

array([[ 45,  17,  26],
       [102,  62,  82],
       [157,  77, 109]])

In [25]:
temp = np.matmul(np.linalg.inv(v), np.linalg.inv(u))
temp

array([[ 0.46638655,  0.15651261, -0.2289916 ],
       [ 1.84453782,  0.8644958 , -1.09033613],
       [-1.97478992, -0.83613445,  1.1092437 ]])

In [30]:
np.matmul(w, temp).round()

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [31]:
np.matmul(temp, w).round()

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])