In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 13)

array([13, 13, 13, 13, 13, 13, 13, 13, 13, 13])

In [5]:
a = np.array([1, 2, 3, 4, 5])
print(a)

print(type(a))

a[2] = 13
print(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 1  2 13  4  5]


In [6]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [8]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((4, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.random.seed(13)
np.random.randn(5, 2)

array([[-0.71239066,  0.75376638],
       [-0.04450308,  0.45181234],
       [ 1.34510171,  0.53233789],
       [ 1.3501879 ,  0.86121137],
       [ 1.47868574, -1.04537713]])

In [11]:
np.random.seed(13)
np.random.randint(low=1, high=100, size=(5,2))

array([[83, 49],
       [75, 17],
       [99, 26],
       [59, 27],
       [67, 47]])

In [12]:
np.arange(0, 111, 10).reshape(4, 3)

array([[  0,  10,  20],
       [ 30,  40,  50],
       [ 60,  70,  80],
       [ 90, 100, 110]])

In [13]:
np.linspace(0, 110, 12).reshape(4, 3)

array([[  0.,  10.,  20.],
       [ 30.,  40.,  50.],
       [ 60.,  70.,  80.],
       [ 90., 100., 110.]])

In [14]:
a = np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
a + 13

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [16]:
a * 7

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84])

In [17]:
b = (10 + (a * 2)) ** 2 / 100
b

array([ 1.  ,  1.44,  1.96,  2.56,  3.24,  4.  ,  4.84,  5.76,  6.76,
        7.84,  9.  , 10.24, 11.56])

In [18]:
a + b

array([ 1.  ,  2.44,  3.96,  5.56,  7.24,  9.  , 10.84, 12.76, 14.76,
       16.84, 19.  , 21.24, 23.56])

In [19]:
a > 7

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True])

In [20]:
a[a > 7]

array([ 8,  9, 10, 11, 12])

In [21]:
a.max()

np.int64(12)

In [22]:
a.mean()

np.float64(6.0)

In [23]:
a.std()

np.float64(3.7416573867739413)

In [30]:
u = np.arange(1, 10).reshape(3, 3)
u

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
u[0, 1]

np.int64(2)

In [32]:
u[1]

array([4, 5, 6])

In [34]:
u[:,1]

array([2, 5, 8])

In [35]:
u[2] = [13, 13, 13]
u

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 13, 13]])

In [36]:
u[:,1] = [6, 7, 9]
u

array([[ 1,  6,  3],
       [ 4,  7,  6],
       [13,  9, 13]])