In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
u + v

array([3, 4, 5, 8])

In [5]:
# Dot product
u * v

array([ 2,  0,  0, 12])

In [7]:
np.dot(u, v)

np.int64(14)

In [8]:
u.dot(v)

np.int64(14)